language: rust
rust:
  - beta
  - nightly
matrix:
  fast_finish: true
before_script:
  - rustup component add clippy || true
  - |
    if [ "$TRAVIS_RUST_VERSION" = "beta" ]; then
      rustup component add rustfmt;
    fi
script:
  - |
    if [ "$TRAVIS_RUST_VERSION" = "beta" ]; then
      cargo fmt -- --check;
    fi
  - cargo --version && rustc --version
  - cargo build --verbose --all
  - rustup component list | grep clippy && cargo clippy --all || echo 'no clippy'
  - cargo test --all
  - cargo doc
cache: cargo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
    rust: nightly
